resolver: lts-7.19

packages:
- '.'

# LTS(安定版 resolver)のPandoc関係ライブラリは古いので、下記に従って依存パッケージを明示する:
# https://github.com/jgm/pandoc-citeproc/blob/master/stack.yaml
extra-deps:
- pandoc-1.19.2
- skylighting-0.1.1.4
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- texmath-0.9

flags: {}
extra-package-dbs: []
